#!/usr/bin/env python
# coding: utf-8

# In[ ]:


import os
import glob,csv
import pandas as pd


# In[ ]:


#This script serves the purpose of sorting the CSVs generated by TrackMate in ImageJ. The naming of the files is
#as follows: 'dev3-pil3-dis1-rep1'=device no.3, pillar confinment C = 3, disorder D = 1, and the repitition 1 for the same condition

upperdir = '/'.join(os.getcwd().split('/')[:-1]) #returns the current working directory

lowerdir = upperdir + '/tracks/' #assuming the data files are in the sub-folder called tracks

files = glob.glob(lowerdir + '*.csv') #grab all the files in their pathways 
files = sorted(files) #sort the pathways based on naming; for example, '/.../dev3-pil1-dis1-rep1.csv' followed by '/.../dev3-pil1-dis1-rep2.csv'

for file in files: 
    sorted_df = pd.read_csv(file, low_memory=False) #Input file: 'dev3-pil3-dis1-rep1.csv'
    sorted_df= sorted_df[3:] #remove the first three rows that are unnecessary
    sorted_df['TRACK_ID'] = sorted_df['TRACK_ID'].astype(int) #convert all the track_id number to integers
    sorted_df['POSITION_T'] = sorted_df['POSITION_T'].astype(float) #convert all the position_t points to floats
    sorted_df['POSITION_X'] = sorted_df['POSITION_X'].astype(float)
    sorted_df['POSITION_Y'] = sorted_df['POSITION_Y'].astype(float)
    sorted_df = sorted_df.sort_values(by=['TRACK_ID','POSITION_T']) #sort the CSV files based on track_id and position_t
    output_file = '/'.join(file.split('/')[:-2])+'/sorted_tracks/sorted-'+file.split('/')[-1] #Write out the output file name with its pathway
    #print(sorted_df)
    sorted_df.to_csv(output_file,index=False) #Output file:'/.../sorted-dev3-pil3-dis1-rep1.csv', yes, that's what we need

